### ISSUE TITLE
[FEAT] What settings are needed to support Chinese?

### ISSUE THREAD

**Issue by TaiYouWeb** [linuxserver/docker-obsidian#13]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

Support for Chinese.

### Reason for change

The display is currently showing gibberish.

**Comment by Fricsion** [comment]
Literally the same thing for Japanese except it shows nothing when I type/paste Japanese text instead of gibberish

**Comment by j0nnymoe** [comment]
Using this mod should fix it: https://github.com/linuxserver/docker-mods/tree/universal-internationalization

**Comment by Fricsion** [comment]
> Using this mod should fix it: https://github.com/linuxserver/docker-mods/tree/universal-internationalization

Tested on Firefox, macOS sequoia

Downloading took very long but eventually started the web app.

But it didn't do the trick for me. I cannot type Japanese texts
