### ISSUE TITLE
[FEAT] what about an opensource PKM: Logseq?

### ISSUE THREAD

**Issue by punkyard** [linuxserver/docker-obsidian#14]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

note taking and personal knowledge management app, but opensource as linux-server.io promotes its commitment with opensource philosophy, wouldn't be nice to have an opensource KPM instead of Obsidian proprietary software?

### Reason for change

proprietary Obsidian > opensource Logseq

**Comment by punkyard** [comment]
> Thanks for opening your first issue here! Be sure to follow the relevant issue templates, or risk having this issue marked as invalid.

well I don't know whet else to say...

**Comment by aptalca** [comment]
Off topic
