### ISSUE TITLE
[BUG]  extension "XFree86-VidModeExtension" missing on display

### ISSUE THREAD

**Issue by masterwishx** [linuxserver/docker-obsidian#2]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Working Fine but have spamming error in Log : 

![image](https://github.com/linuxserver/docker-obsidian/assets/28630321/306979d5-04eb-456a-9181-6027e6af1d33)

![image](https://github.com/linuxserver/docker-obsidian/assets/28630321/d886d0f6-c6eb-450e-b7da-0678501fd843)

### Steps To Reproduce

Running latest version on docker in Unraid x64

### Environment

```markdown
- OS:
- How docker service was installed:

Docker in Unraid 6.12.10
```

### CPU architecture

x86-64

### Docker creation

```bash
.
```

### Container logs

```bash
.
```

**Comment by quietsy** [comment]
Should be fixed on the latest after you delete `/config/.config/openbox` and restart the container.

**Comment by masterwishx** [comment]
> Should be fixed on the latest after you delete `/config/.config/openbox` and restart the container.

Thanks a lot, working fine now
