### ISSUE TITLE
[BUG]  [PRIO] Input: Failure adding new keysym 0x10065af

### ISSUE THREAD

**Issue by cszs1986** [linuxserver/docker-obsidian#5]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

 [PRIO] Input: Failure adding new keysym 0x10065af

### Steps To Reproduce

 [PRIO] Input: Failure adding new keysym 0x10065af

### Environment

```markdown
- OS:
- How docker service was installed:
```

### CPU architecture

x86-64

### Docker creation

```bash
 [PRIO] Input: Failure adding new keysym 0x10065af
```

### Container logs

```bash
 [PRIO] Input: Failure adding new keysym 0x10065af
```

**Comment by Roxedus** [comment]
In English please, we have no capabilities to offer support in other languages.

**Comment by cszs1986** [comment]
![微信截图_20240422115724](https://github.com/linuxserver/docker-obsidian/assets/30801827/ec2dd57a-82b9-4f6d-bee2-e8bdad6d91db)

**Comment by cszs1986** [comment]
Chinese input 

> ![微信截图_20240422115724](https://private-user-images.githubusercontent.com/30801827/324323808-ec2dd57a-82b9-4f6d-bee2-e8bdad6d91db.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM3NTg1NTcsIm5iZiI6MTcxMzc1ODI1NywicGF0aCI6Ii8zMDgwMTgyNy8zMjQzMjM4MDgtZWMyZGQ1N2EtODJiOS00ZjZkLWJlZTItZThiZGFkNmQ5MWRiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIyVDAzNTczN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgzZDk0NWI0YTdmMzQ0ZmZkMjQ1MDY0M2E2MDdkNjRiMTg4ODFhMGFiZmE1NjE1MjU4MDQyNzRiZWEzMmJmZDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.e9OJ6jI2pYHG2Esy2p0v5EyfnWeUNvrb5mr9w1wjLjg)

 Chinese input
