### ISSUE TITLE
[BUG] Black screen in KASM

### ISSUE THREAD

**Issue by tuxpeople** [linuxserver/docker-obsidian#7]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I added the linuxserver.io Registry to my KASM Installation. When I start Obsidian, all I get is a black screen. It looks like this black screen is coming from the window manager, as I can change between 4 desktops using swipe gestures and I get a little context menu to start terminal and chromium if I do a right-click into the black screen:

<img width="237" alt="image" src="https://github.com/linuxserver/docker-obsidian/assets/1506076/1f6b6842-9374-4b52-98cf-d40118614167">

### Expected Behavior

I see Obsidian and can user it.

### Steps To Reproduce

1. I Installed KASM 1.15.0.577587 on Ubuntu 24.04 (x86_64) with Docker version 26.1.3, build b72abbb
2. I added https://kasmregistry.linuxserver.io/ as KASM registry
3. I installed the Obsidian Workspace from said Registry. It's using `lscr.io/linuxserver/obsidian:latest`, docker image inspect says build_version is `Linuxserver.io version:- v1.5.12-ls9 Build-date:- 2024-05-26T11:51:21+00:00`
4. I started the installed Obsidian Workspace

Step 1 has been done using this script:
```shell
sudo /bin/dd if=/dev/zero of=/var/swap.1 bs=1M count=2048
sudo /sbin/mkswap /var/swap.1
sudo chmod 600 /var/swap.1
sudo /sbin/swapon /var/swap.1
echo '/var/swap.1 swap swap defaults 0 0' | sudo tee -a /etc/fstab
curl -fsSL https://get.docker.com | sudo sh
wget $(curl -s https://api.github.com/repos/kasmtech/kasm-install-wizard/releases/latest | jq -r .assets[0].browser_download_url) -O /tmp/kasm_workspaces.tar.gz
cd /tmp
tar -xf kasm_workspaces.tar.gz
sudo bash /tmp/kasm_release/install.sh noninteractive -e -p $(hostname -I | cut -d' ' -f1 | tr -d '\\n') -m $(hostname -I | cut -d' ' -f1 | tr -d '\\n') | grep 'Login Credentials' -A 50 | grep -v DataSourceVMware | sudo tee /root/kasm-passwords.txt >/dev/null 2>&1
```

### Environment

```markdown
KASM: 1.15.0.577587
OS: Ubuntu 24.04 (x86_64)
Docker: 26.1.3, build b72abbb
```

### CPU architecture

x86-64

### Docker creation

<img width="707" alt="image" src="https://github.com/linuxserver/docker-obsidian/assets/1506076/8d882c50-0cad-4871-b3b3-8b089076f718">
<img width="431" alt="image" src="https://github.com/linuxserver/docker-obsidian/assets/1506076/a4121792-7e51-4ebb-87a7-13b26b9aebb6">
<img width="432" alt="image" src="https://github.com/linuxserver/docker-obsidian/assets/1506076/e05a26df-ad50-43b6-81e9-6fae7e03bb7a">

### Container logs

[kasm-obsidian-log.json](https://github.com/linuxserver/docker-obsidian/files/15467486/kasm-obsidian-log.json)

**Comment by turkievicz** [comment]
I have the same issue, but I "fixed" opening xterm and `sudo /opt/obsidian/obsidian --no-sandbox`

**Comment by DuelistRag3** [comment]
ok nevermind, got it with docker exec config working:
`
{
  "first_launch": {
    "user": "root",
    "cmd": "bash -c 'chmod -R 777 /opt/obsidian/'"
  }
}
`

**Comment by tuxpeople** [comment]
> > ok nevermind, got it with docker exec config working: `{ "first_launch": { "user": "root", "cmd": "bash -c 'chmod -R 777 /opt/obsidian/'" } }`
> 
> This fixed the issue for me, thanks!

Can also confirm the fix. I think that fix schould go into the image or at least into the KASM registry of linuxserver.

**Comment by saberxt** [comment]
I have same problem but a little difference.

I can use obsidian for a minute or two then it becomes black.

**Comment by thelamer** [comment]
Does anyone know the directories that need to be symlinked into the users $HOME, this would be the best approach.

**Comment by DuelistRag3** [comment]
> Does anyone know the directories that need to be symlinked into the users $HOME, this would be the best approach.

same directorys as mentioned in my comment

**Comment by thelamer** [comment]
This has been resolved with the latest image, if there is any persistence linked to your existing container the `/home/kasm-user/.openbox/autostart` file will need to be deleted.
